# permissions for end users to edit redirecturisyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redirecturisync-editor-role
rules:
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - redirecturisyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - redirecturisyncs/status
  verbs:
  - get
