# permissions for end users to view replyurlsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replyurlsync-viewer-role
rules:
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - replyurlsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - replyurlsyncs/status
  verbs:
  - get
