# permissions for end users to edit replyurlsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replyurlsync-editor-role
rules:
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - replyurlsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - replyurlsyncs/status
  verbs:
  - get
