---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-role
rules:
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - replyurlsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - replyurlsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - appregistrations.azure.hmcts.net
  resources:
  - replyurlsyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
