name: Create Tag

on:
  pull_request:
    types:
      - closed
env:
  # Common vars
  GITHUB_EVENT_NUMBER: ${{ github.event.number }}
  APP_NAME: reply-urls-operator
  VAR_FILE_PATH: ${{ github.workspace }}/.github/workflows

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set tag version
        id: tagVersion
        run: |
          version=$(echo "${{ env.GITHUB_EVENT_NUMBER }} 100" | awk '{printf "%.2f", $1 / $2}')
          ::set-output name=tagVersion::$version

      - uses: rickstaa/action-create-tag@v1
        with:
         tag: steps.tagVersion.outputs.tagVersion
         message: "Tag of the Reply URLs Operator"
